import { type ReactNode, useEffect, useMemo, useState } from 'react';
import { Link, Redirect, Route, Switch, useLocation, useParams, Router as WouterRouter } from 'wouter';
import {
  AlertTriangle, Archive, ArrowLeft, BarChart3, Check, ChevronRight, CircleDollarSign,
  Clock3, FolderTree, LayoutDashboard, Loader2, LogOut, Menu, Megaphone, MessageSquare,
  MoreHorizontal, Package, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck,
  Trash2, UserCog, Users, X, XCircle,
} from 'lucide-react';
import { adminApi, type Advertisement, type AdminProduct, type Category, type ContactMessage, type Duration, type Payment, type Report, type User } from '@/lib/shinex-admin-api';
import { getToken, setToken } from '@/lib/shinex-admin-api';
import { ErrorBoundary } from '@/components/error-boundary';
import NotFound from '@/pages/not-found';

type Load<T> = { data: T | null; loading: boolean; error: string | null; reload: () => void };
function useLoad<T>(loader: () => Promise<T>, deps: unknown[]): Load<T> {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [version, setVersion] = useState(0);
  useEffect(() => {
    let active = true;
    setLoading(true); setError(null);
    loader().then((value) => active && setData(value)).catch((reason: unknown) => active && setError(reason instanceof Error ? reason.message : 'Unable to load data')).finally(() => active && setLoading(false));
    return () => { active = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [...deps, version]);
  return { data, loading, error, reload: () => setVersion((current) => current + 1) };
}

const formatDate = (date?: string | null) => date ? new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(date)) : 'Not provided';
const formatMoney = (value?: number | null) => typeof value === 'number' ? `₦${value.toLocaleString('en-NG')}` : 'Not provided';
const short = (value?: string | null, length = 10) => value ? `${value.slice(0, length)}${value.length > length ? '…' : ''}` : '—';
const errorMessage = (error: unknown) => error instanceof Error ? error.message : 'Action could not be completed.';

function StatusBadge({ value }: { value?: string | boolean | null }) {
  const label = typeof value === 'boolean' ? value ? 'Active' : 'Inactive' : value || 'Unavailable';
  const tone = ['approved', 'active', 'success', 'paid', 'read', 'resolved', 'replied'].includes(String(value)) ? 'good' : ['rejected', 'failed', 'dismissed', 'suspended', 'paused'].includes(String(value)) ? 'bad' : 'wait';
  return <span data-testid={`status-${String(value || 'unavailable')}`} className={`status-badge status-${tone}`}>{label}</span>;
}

function EmptyState({ title, detail = 'There are no records matching this view.', action }: { title: string; detail?: string; action?: ReactNode }) {
  return <div className="empty-state" data-testid="empty-state"><div className="empty-mark"><Archive size={20} /></div><h3>{title}</h3><p>{detail}</p>{action}</div>;
}
function PageError({ message, retry }: { message: string; retry: () => void }) {
  return <div className="state-card state-error" data-testid="error-state"><AlertTriangle size={20} /><div><strong>Could not load this view</strong><p>{message}</p><button className="button button-quiet" onClick={retry} data-testid="button-retry"><RefreshCw size={14} /> Retry</button></div></div>;
}
function SkeletonTable() {
  return <div className="panel" data-testid="loading-state"><div className="skeleton skeleton-title" />{Array.from({ length: 5 }).map((_, index) => <div className="skeleton skeleton-row" key={index} />)}</div>;
}
function ConfirmButton({ label, onConfirm, danger = false, disabled = false }: { label: string; onConfirm: () => void; danger?: boolean; disabled?: boolean }) {
  return <button disabled={disabled} className={`button ${danger ? 'button-danger' : 'button-quiet'}`} onClick={() => { if (window.confirm(`Confirm: ${label}?`)) onConfirm(); }} data-testid={`button-${label.toLowerCase().replaceAll(' ', '-')}`}><Trash2 size={14} /> {label}</button>;
}

const nav = [
  { href: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { href: '/users', label: 'Users', icon: Users },
  { href: '/products', label: 'Products', icon: Package },
  { href: '/categories', label: 'Categories', icon: FolderTree },
  { href: '/advertisements', label: 'Advertisements', icon: Megaphone },
  { href: '/durations', label: 'Ad pricing', icon: Clock3 },
  { href: '/payments', label: 'Payments', icon: CircleDollarSign },
  { href: '/reports', label: 'Reports', icon: BarChart3 },
  { href: '/contact', label: 'Contact', icon: MessageSquare },
  { href: '/admin-management', label: 'Admin access', icon: ShieldCheck },
];

function Shell({ user, children }: { user: User; children: ReactNode }) {
  const [location, setLocation] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const current = nav.find((item) => location === item.href || location.startsWith(`${item.href}/`));
  const logout = async () => { try { await adminApi.auth.logout(); } finally { setToken(null); setLocation('/login'); } };
  return <div className="admin-shell noise">
    <aside className={`sidebar ${mobileOpen ? 'sidebar-open' : ''}`} data-testid="admin-sidebar">
      <div className="sidebar-brand"><div className="brand-symbol">S</div><div className="sidebar-brand-copy"><strong>SHINEX</strong><span>MARKETPLACE</span></div><button className="mobile-close" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X size={18} /></button></div>
      <nav className="sidebar-nav" aria-label="Admin navigation">{nav.map(({ href, label, icon: Icon }) => <Link href={href} key={href} onClick={() => setMobileOpen(false)} className={`sidebar-link ${location === href || location.startsWith(`${href}/`) ? 'sidebar-link-active' : ''}`} data-testid={`link-${label.toLowerCase().replaceAll(' ', '-')}`}><Icon size={17} /><span className="sidebar-label">{label}</span></Link>)}</nav>
      <div className="sidebar-footer"><div className="account-mini"><div className="initials">{(user.full_name || user.username || 'A').slice(0, 1).toUpperCase()}</div><div className="sidebar-label"><strong>{user.full_name || user.username}</strong><span>Administrator</span></div></div><button className="logout-button" onClick={logout} data-testid="button-logout"><LogOut size={16} /><span className="sidebar-label">Sign out</span></button></div>
    </aside>
    <main className="content-offset">
      <header className="topbar"><button className="menu-button" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><div><span className="eyebrow">SHINEX CONTROL ROOM</span><h1 data-testid="page-title">{current?.label || 'Administration'}</h1></div><div className="topbar-account"><span className="online-dot" />{user.full_name || user.username}<span className="role-pill">ADMIN</span></div></header>
      <div className="page-wrap app-enter">{children}</div>
    </main>
  </div>;
}

function AuthGate({ children }: { children: (user: User) => ReactNode }) {
  const [state, setState] = useState<'loading' | 'authorized' | 'unauthorized' | 'signed-out'>('loading');
  const [user, setUser] = useState<User | null>(null);
  const [location, setLocation] = useLocation();
  useEffect(() => {
    if (!getToken()) { setState('signed-out'); return; }
    let active = true;
    adminApi.auth.me().then(async (account) => {
      await adminApi.users.list({ limit: 1 });
      if (active) { setUser(account); setState('authorized'); }
    }).catch((error: unknown) => {
      if (!active) return;
      if ((error as { status?: number }).status === 401) { setToken(null); setState('signed-out'); }
      else setState('unauthorized');
    });
    return () => { active = false; };
  }, [setLocation]);
  if (state === 'loading') return <div className="auth-loading"><div className="brand-lockup"><div className="brand-symbol">S</div><strong>SHINEX</strong></div><div className="skeleton auth-loader" /><p>Verifying administrator access with SHINEX...</p></div>;
  if (state === 'signed-out') return <Redirect to={`/login?next=${encodeURIComponent(location)}`} />;
  if (state === 'unauthorized') return <Unauthorized onSignOut={() => { setToken(null); setState('signed-out'); }} />;
  return user ? <Shell user={user}>{children(user)}</Shell> : null;
}

function Unauthorized({ onSignOut }: { onSignOut: () => void }) {
  return <div className="auth-loading"><div className="access-denied"><ShieldCheck size={30} /><span>ADMIN ACCESS REQUIRED</span></div><h1>This account is not authorized</h1><p>SHINEX confirmed your session, but the backend did not grant administrator access. URL navigation cannot bypass this check.</p><button className="button button-primary" onClick={onSignOut} data-testid="button-unauthorized-signout"><LogOut size={15} /> Sign out</button></div>;
}

function Login() {
  const [, setLocation] = useLocation();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setBusy(true); setError('');
    try {
      const result = await adminApi.auth.login({ email, password });
      setToken(result.token);
      await adminApi.auth.me();
      await adminApi.users.list({ limit: 1 });
      setLocation('/dashboard');
    } catch (reason) { setToken(null); setError(errorMessage(reason)); } finally { setBusy(false); }
  };
  return <div className="login-screen"><div className="login-aside"><div className="brand-lockup"><div className="brand-symbol">S</div><div><strong>SHINEX</strong><span>MARKETPLACE</span></div></div><div className="login-aside-copy"><span className="eyebrow">ADMINISTRATOR CONSOLE</span><h1>Keep the marketplace<br /><em>moving well.</em></h1><p>Moderate listings, protect the community, and keep every marketplace surface accountable.</p></div><span className="login-caption">Secure access is decided by the SHINEX backend.</span></div><div className="login-form-wrap"><form className="login-card" onSubmit={submit}><div className="mobile-login-brand"><div className="brand-symbol">S</div><strong>SHINEX</strong></div><span className="eyebrow">WELCOME BACK</span><h1>Sign in to admin</h1><p className="muted">Use your existing SHINEX account. Admin access is verified after authentication.</p>{error && <div className="form-error" data-testid="login-error"><AlertTriangle size={16} />{error}</div>}<label>Email address<input data-testid="input-email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<input data-testid="input-password" type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><button className="button button-primary button-wide" disabled={busy} type="submit" data-testid="button-login">{busy ? <Loader2 className="spin" size={16} /> : <ShieldCheck size={16} />}{busy ? 'Checking credentials...' : 'Sign in securely'}</button><p className="form-footnote">Not an administrator? Your account will be denied by the backend.</p></form></div></div>;
}

function PageHeader({ eyebrow, title, detail, action }: { eyebrow?: string; title: string; detail?: string; action?: ReactNode }) {
  return <div className="page-header"><div><span className="eyebrow">{eyebrow || 'WORKSPACE'}</span><h2>{title}</h2>{detail && <p>{detail}</p>}</div>{action && <div className="page-header-action">{action}</div>}</div>;
}
function Toolbar({ children }: { children: ReactNode }) { return <div className="toolbar">{children}</div>; }
function Input({ value, onChange, placeholder, type = 'text', testId }: { value: string; onChange: (value: string) => void; placeholder?: string; type?: string; testId: string }) { return <input data-testid={testId} className="input" value={value} type={type} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} />; }
function ActionButton({ children, onClick, primary = false, disabled = false, testId }: { children: ReactNode; onClick: () => void; primary?: boolean; disabled?: boolean; testId: string }) { return <button className={`button ${primary ? 'button-primary' : 'button-quiet'}`} onClick={onClick} disabled={disabled} data-testid={testId}>{children}</button>; }
function Pagination({ page, totalPages, onChange }: { page: number; totalPages?: number; onChange: (page: number) => void }) { if (!totalPages || totalPages <= 1) return null; return <div className="pagination"><button className="button button-quiet" disabled={page <= 1} onClick={() => onChange(page - 1)} data-testid="button-page-previous">Previous</button><span>Page {page} of {totalPages}</span><button className="button button-quiet" disabled={page >= totalPages} onClick={() => onChange(page + 1)} data-testid="button-page-next">Next</button></div>; }

function Dashboard() {
  const [reload, setReload] = useState(0);
  const [data, setData] = useState<{ users?: number; activeUsers?: number; suspendedUsers?: number; products?: number; pendingProducts?: number; approvedProducts?: number; ads?: number; payments?: number; reports?: number; contacts?: number; revenue?: number; breakdown?: Array<{ status: string; count: number }> }>({});
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { let active = true; setLoading(true); setError('');
    Promise.all([
      adminApi.users.list({ limit: 1 }),
      adminApi.users.list({ status: 'active', limit: 1 }),
      adminApi.users.list({ status: 'suspended', limit: 1 }),
      adminApi.products.list({ limit: 1 }),
      adminApi.products.list({ status: 'pending', limit: 1 }),
      adminApi.products.list({ status: 'approved', limit: 1 }),
      adminApi.advertisements.list({ approval: 'pending', limit: 1 }),
      adminApi.payments.list({ limit: 1 }),
      adminApi.payments.stats(),
      adminApi.reports.list({ status: 'pending', limit: 1 }),
      adminApi.contact.list({ status: 'new', limit: 1 }),
    ]).then(([users, activeUsers, suspendedUsers, products, pendingProducts, approvedProducts, ads, payments, stats, reports, contacts]) => { if (active) setData({ users: users.pagination?.total, activeUsers: activeUsers.pagination?.total, suspendedUsers: suspendedUsers.pagination?.total, products: products.pagination?.total, pendingProducts: pendingProducts.pagination?.total, approvedProducts: approvedProducts.pagination?.total, ads: ads.pagination?.total, payments: payments.pagination?.total, reports: reports.pagination?.total, contacts: contacts.pagination?.total, revenue: stats.total_revenue, breakdown: stats.status_breakdown }); }).catch((reason) => active && setError(errorMessage(reason))).finally(() => active && setLoading(false));
    return () => { active = false; };
  }, [reload]);
  const cards = [{ label: 'Total users', value: data.users, icon: Users, href: '/users' }, { label: 'Active users', value: data.activeUsers, icon: Users, href: '/users?status=active' }, { label: 'Suspended users', value: data.suspendedUsers, icon: XCircle, href: '/users?status=suspended' }, { label: 'Products', value: data.products, icon: Package, href: '/products' }, { label: 'Pending products', value: data.pendingProducts, icon: Clock3, href: '/products?status=pending' }, { label: 'Approved products', value: data.approvedProducts, icon: Check, href: '/products?status=approved' }, { label: 'Pending ads', value: data.ads, icon: Megaphone, href: '/advertisements' }, { label: 'Payments', value: data.payments, icon: CircleDollarSign, href: '/payments' }, { label: 'Open reports', value: data.reports, icon: BarChart3, href: '/reports' }, { label: 'New messages', value: data.contacts, icon: MessageSquare, href: '/contact' }];
  return <><PageHeader eyebrow="OVERVIEW" title="Dashboard" detail="A live view of the marketplace moderation queue." action={<ActionButton onClick={() => setReload((value) => value + 1)} testId="button-refresh-dashboard"><RefreshCw size={15} /> Refresh data</ActionButton>} />{error ? <PageError message={error} retry={() => setReload((value) => value + 1)} /> : loading ? <div className="metric-grid">{cards.map((card) => <div className="metric-card" key={card.label}><div className="skeleton metric-skeleton" /></div>)}</div> : <><div className="metric-grid">{cards.map(({ label, value, icon: Icon, href }) => <Link href={href} className="metric-card" key={label} data-testid={`metric-${label.toLowerCase().replaceAll(' ', '-')}`}><div className="metric-top"><span>{label}</span><Icon size={17} /></div><strong>{typeof value === 'number' ? value.toLocaleString() : 'Unavailable'}</strong><span className="metric-link">View records <ChevronRight size={13} /></span></Link>)}</div><div className="dashboard-lower"><div className="panel dashboard-revenue"><div className="panel-heading"><div><span className="eyebrow">PAYMENT STATS</span><h3>Revenue captured</h3></div><CircleDollarSign size={21} /></div><strong className="revenue-value">{typeof data.revenue === 'number' ? formatMoney(data.revenue) : 'Unavailable'}</strong><p className="muted">Provided by the backend payment summary endpoint. No estimates are shown.</p></div><div className="panel"><div className="panel-heading"><div><span className="eyebrow">PAYMENT STATUS</span><h3>Transaction breakdown</h3></div></div>{data.breakdown?.length ? <div className="breakdown-list">{data.breakdown.map((item) => <div className="breakdown-row" key={item.status}><StatusBadge value={item.status} /><strong>{item.count}</strong></div>)}</div> : <EmptyState title="No payment breakdown" detail="The backend returned no payment status records." />}</div></div></>}</>;
}

function UsersPage({ management = false }: { management?: boolean }) {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [saving, setSaving] = useState('');
  const result = useLoad(() => adminApi.users.list({ search, status, page, limit: 20 }), [search, status, page]);
  const users = result.data?.data || [];
  const toggleAdmin = async (user: User) => { setSaving(user.id); try { await adminApi.users.setAdmin(user.id, !user.is_admin); result.reload(); } catch (error) { window.alert(errorMessage(error)); } finally { setSaving(''); } };
  const toggleSuspend = async (user: User) => { setSaving(user.id); try { if (user.is_suspended) await adminApi.users.unsuspend(user.id); else { const reason = window.prompt('Suspension reason', 'Violation of marketplace guidelines'); if (reason === null) return; await adminApi.users.suspend(user.id, reason); } result.reload(); } catch (error) { window.alert(errorMessage(error)); } finally { setSaving(''); } };
  const deleteUser = async (user: User) => { if (!window.confirm(`Delete ${user.full_name || user.username}? This cannot be undone.`)) return; setSaving(user.id); try { await adminApi.users.remove(user.id); result.reload(); } catch (error) { window.alert(errorMessage(error)); } finally { setSaving(''); } };
  return <><PageHeader eyebrow={management ? 'ACCESS CONTROL' : 'PEOPLE'} title={management ? 'Admin management' : 'Users'} detail={management ? 'Grant or revoke the backend-enforced administrator privilege.' : 'Search accounts and manage their marketplace access.'} />{!management && <Toolbar><div className="search-box"><Search size={16} /><Input value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Search name, username or email" testId="input-user-search" /></div><select className="select" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} data-testid="select-user-status"><option value="">All users</option><option value="active">Active</option><option value="suspended">Suspended</option></select></Toolbar>}{management && <div className="notice"><ShieldCheck size={17} /><span>Only the backend can enforce this change. The button calls the documented set-admin endpoint and does not alter a local flag.</span></div>}{result.loading ? <SkeletonTable /> : result.error ? <PageError message={result.error} retry={result.reload} /> : users.length === 0 ? <EmptyState title={management ? 'No administrators found in this view' : 'No users found'} detail="Try a different filter or search term." /> : <div className="panel"><div className="scroll-table"><table className="data-table"><thead><tr><th>User</th><th>Contact</th><th>Joined</th><th>Admin</th><th>Access</th><th>Actions</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} data-testid={`row-user-${user.id}`}><td><Link className="table-primary" href={`/users/${user.id}`}>{user.full_name || user.username}</Link><span className="table-secondary">@{user.username}</span></td><td><span>{user.email}</span><span className="table-secondary">{user.phone || 'Phone not provided'}</span></td><td>{formatDate(user.created_at)}</td><td><StatusBadge value={user.is_admin ? 'approved' : 'standard'} /></td><td><StatusBadge value={user.is_suspended ? 'suspended' : 'active'} /></td><td><div className="table-actions">{management ? <ActionButton onClick={() => toggleAdmin(user)} disabled={saving === user.id} testId={`button-toggle-admin-${user.id}`}>{user.is_admin ? <XCircle size={14} /> : <ShieldCheck size={14} />}{user.is_admin ? 'Revoke' : 'Grant'}</ActionButton> : <><ActionButton onClick={() => toggleSuspend(user)} disabled={saving === user.id} testId={`button-toggle-suspend-${user.id}`}>{user.is_suspended ? <Check size={14} /> : <XCircle size={14} />}{user.is_suspended ? 'Unsuspend' : 'Suspend'}</ActionButton><ConfirmButton label="Delete" onConfirm={() => deleteUser(user)} danger disabled={saving === user.id} /></>}</div></td></tr>)}</tbody></table></div><Pagination page={page} totalPages={result.data?.pagination?.totalPages} onChange={setPage} /></div>}</>;
}

function UserDetail({ userId }: { userId: string }) {
  const result = useLoad(() => adminApi.users.get(userId), [userId]); const [saving, setSaving] = useState(false); const [, setLocation] = useLocation();
  if (result.loading) return <><PageHeader title="User details" /><SkeletonTable /></>;
  if (result.error || !result.data) return <PageError message={result.error || 'User not found'} retry={result.reload} />;
  const user = result.data;
  const toggle = async () => { setSaving(true); try { if (user.is_suspended) await adminApi.users.unsuspend(user.id); else await adminApi.users.suspend(user.id, window.prompt('Suspension reason', 'Violation of marketplace guidelines') || 'No reason provided'); result.reload(); } catch (error) { window.alert(errorMessage(error)); } finally { setSaving(false); } };
  return <><button className="back-link" onClick={() => setLocation('/users')} data-testid="button-back-users"><ArrowLeft size={15} /> Back to users</button><PageHeader eyebrow="USER RECORD" title={user.full_name || user.username} detail={`@${user.username} · ${user.email}`} action={<ActionButton onClick={toggle} disabled={saving} testId="button-detail-suspend">{user.is_suspended ? <Check size={15} /> : <XCircle size={15} />}{user.is_suspended ? 'Unsuspend account' : 'Suspend account'}</ActionButton>} /><div className="detail-grid"><div className="panel detail-main"><div className="profile-heading"><div className="avatar-large">{(user.full_name || user.username).slice(0, 1).toUpperCase()}</div><div><span className="eyebrow">ACCOUNT</span><h3>{user.full_name || user.username}</h3><p>{user.email}</p></div></div><div className="field-grid"><div><span className="field-label">Username</span><strong>@{user.username}</strong></div><div><span className="field-label">Phone</span><strong>{user.phone || 'Not provided'}</strong></div><div><span className="field-label">Joined</span><strong>{formatDate(user.created_at)}</strong></div><div><span className="field-label">Authorization</span><StatusBadge value={user.is_admin ? 'approved' : 'standard'} /></div><div><span className="field-label">Account access</span><StatusBadge value={user.is_suspended ? 'suspended' : 'active'} /></div></div></div><div className="panel"><div className="panel-heading"><div><span className="eyebrow">ACTIVITY COUNTS</span><h3>Backend-reported totals</h3></div></div><div className="mini-stats"><div><strong>{user.stats?.products ?? 'Unavailable'}</strong><span>Products</span></div><div><strong>{user.stats?.advertisements ?? 'Unavailable'}</strong><span>Advertisements</span></div><div><strong>{user.stats?.reports ?? 'Unavailable'}</strong><span>Reports</span></div></div></div></div></>;
}

function ProductsPage() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const result = useLoad(() => adminApi.products.list({ search, status, page, limit: 20 }), [search, status, page]); const [saving, setSaving] = useState('');
  const action = async (product: AdminProduct, kind: 'approve' | 'reject' | 'delete') => { setSaving(product.id); try { if (kind === 'approve') await adminApi.products.approve(product.id); if (kind === 'reject') await adminApi.products.reject(product.id, window.prompt('Rejection reason', 'Did not meet marketplace guidelines') || 'Did not meet marketplace guidelines'); if (kind === 'delete') await adminApi.products.remove(product.id); result.reload(); } catch (error) { window.alert(errorMessage(error)); } finally { setSaving(''); } };
  const products = result.data?.data || [];
  return <><PageHeader eyebrow="CATALOG MODERATION" title="Products" detail="Review listings using the statuses returned by the marketplace backend." /><Toolbar><div className="search-box"><Search size={16} /><Input value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Search product name" testId="input-product-search" /></div><select className="select" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} data-testid="select-product-status"><option value="">All products</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="sold">Sold</option></select></Toolbar>{result.loading ? <SkeletonTable /> : result.error ? <PageError message={result.error} retry={result.reload} /> : products.length === 0 ? <EmptyState title="No products found" detail="There are no listings in this filter." /> : <div className="panel"><div className="scroll-table"><table className="data-table"><thead><tr><th>Listing</th><th>Seller</th><th>Category</th><th>Price</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{products.map((product) => <tr key={product.id} data-testid={`row-product-${product.id}`}><td><Link className="table-primary" href={`/products/${product.id}`}>{product.name}</Link><span className="table-secondary">{product.location || 'Location not provided'}</span></td><td>{product.user?.full_name || product.user?.username || product.seller?.username || 'Unavailable'}</td><td>{product.category?.name || 'Uncategorized'}</td><td className="money">{formatMoney(Number(product.price))}</td><td><StatusBadge value={product.approval_status || (product.is_active ? 'active' : 'inactive')} /></td><td>{formatDate(product.created_at)}</td><td><div className="table-actions">{product.approval_status !== 'approved' && <ActionButton onClick={() => action(product, 'approve')} disabled={saving === product.id} testId={`button-approve-product-${product.id}`}><Check size={14} /> Approve</ActionButton>}{product.approval_status !== 'rejected' && <ActionButton onClick={() => action(product, 'reject')} disabled={saving === product.id} testId={`button-reject-product-${product.id}`}><X size={14} /> Reject</ActionButton>}<ConfirmButton label="Delete" onConfirm={() => action(product, 'delete')} danger disabled={saving === product.id} /></div></td></tr>)}</tbody></table></div><Pagination page={page} totalPages={result.data?.pagination?.totalPages} onChange={setPage} /></div>}</>;
}

function ProductDetail({ productId }: { productId: string }) {
  const result = useLoad(() => adminApi.products.get(productId), [productId]); const [, setLocation] = useLocation(); const [saving, setSaving] = useState(false);
  if (result.loading) return <><PageHeader title="Product inspection" /><SkeletonTable /></>; if (result.error || !result.data) return <PageError message={result.error || 'Product not found'} retry={result.reload} />;
  const product = result.data;
  const act = async (type: 'approve' | 'reject' | 'delete') => { setSaving(true); try { if (type === 'approve') await adminApi.products.approve(product.id); if (type === 'reject') await adminApi.products.reject(product.id, window.prompt('Rejection reason', 'Did not meet marketplace guidelines') || 'Did not meet marketplace guidelines'); if (type === 'delete' && window.confirm(`Delete ${product.name}?`)) { await adminApi.products.remove(product.id); setLocation('/products'); return; } result.reload(); } catch (error) { window.alert(errorMessage(error)); } finally { setSaving(false); } };
  return <><button className="back-link" onClick={() => setLocation('/products')} data-testid="button-back-products"><ArrowLeft size={15} /> Back to products</button><PageHeader eyebrow="LISTING INSPECTION" title={product.name} detail={`Created ${formatDate(product.created_at)}`} action={<div className="header-actions"><ActionButton onClick={() => act('approve')} disabled={saving} primary testId="button-detail-approve"><Check size={15} /> Approve</ActionButton><ActionButton onClick={() => act('reject')} disabled={saving} testId="button-detail-reject"><X size={15} /> Reject</ActionButton></div>} /><div className="detail-grid"><div className="panel"><div className="product-preview">{product.primary_image || product.images?.[0]?.image_url ? <img src={product.primary_image || product.images?.[0]?.image_url} alt={product.name} /> : <Package size={36} />}</div><h3>{product.name}</h3><p className="detail-description">{product.description || 'No description provided.'}</p><div className="field-grid"><div><span className="field-label">Price</span><strong className="money">{formatMoney(Number(product.price))}</strong></div><div><span className="field-label">Category</span><strong>{product.category?.name || 'Unavailable'}</strong></div><div><span className="field-label">Location</span><strong>{product.location || 'Unavailable'}</strong></div><div><span className="field-label">Approval</span><StatusBadge value={product.approval_status} /></div></div></div><div className="panel"><div className="panel-heading"><div><span className="eyebrow">SELLER</span><h3>{product.user?.full_name || product.user?.username || 'Unavailable'}</h3></div></div><p className="muted">{product.user?.email || 'Seller email unavailable.'}</p><p className="muted">{product.user?.phone || 'Seller phone unavailable.'}</p><div className="detail-danger"><ConfirmButton label="Delete" onConfirm={() => act('delete')} danger disabled={saving} /></div></div></div></>;
}

function CategoriesPage() {
  const result = useLoad(() => adminApi.categories.list(), []); const [editing, setEditing] = useState<Category | null>(null); const [form, setForm] = useState({ name: '', description: '' }); const [busy, setBusy] = useState(false); const [search, setSearch] = useState('');
  const categories = (result.data || []).filter((category) => `${category.name} ${category.slug}`.toLowerCase().includes(search.toLowerCase()));
  const save = async () => { if (!form.name.trim()) return; setBusy(true); try { if (editing) await adminApi.categories.update(editing.id, form); else await adminApi.categories.create(form); setEditing(null); setForm({ name: '', description: '' }); result.reload(); } catch (error) { window.alert(errorMessage(error)); } finally { setBusy(false); } };
  const edit = (category: Category) => { setEditing(category); setForm({ name: category.name, description: category.description || '' }); };
  return <><PageHeader eyebrow="CATALOG STRUCTURE" title="Categories" detail="Manage the categories used by SHINEX listings." action={<ActionButton primary onClick={() => { setEditing({ id: '', name: '', slug: '' }); setForm({ name: '', description: '' }); }} testId="button-add-category"><Plus size={15} /> Add category</ActionButton>} />{editing && <div className="panel editor-panel"><div className="panel-heading"><div><span className="eyebrow">{editing.id ? 'EDIT CATEGORY' : 'NEW CATEGORY'}</span><h3>{editing.id ? 'Update category' : 'Create category'}</h3></div><button className="icon-button" onClick={() => setEditing(null)} aria-label="Close editor"><X size={17} /></button></div><div className="form-grid"><label>Name<input className="input" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} data-testid="input-category-name" /></label><label>Description<input className="input" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} data-testid="input-category-description" /></label></div><div className="editor-actions"><ActionButton primary onClick={save} disabled={busy} testId="button-save-category">{busy ? 'Saving...' : 'Save category'}</ActionButton></div></div>}<Toolbar><div className="search-box"><Search size={16} /><Input value={search} onChange={setSearch} placeholder="Search categories" testId="input-category-search" /></div></Toolbar>{result.loading ? <SkeletonTable /> : result.error ? <PageError message={result.error} retry={result.reload} /> : categories.length === 0 ? <EmptyState title="No categories found" /> : <div className="panel"><div className="scroll-table"><table className="data-table"><thead><tr><th>Category</th><th>Description</th><th>Status</th><th>Actions</th></tr></thead><tbody>{categories.map((category) => <tr key={category.id} data-testid={`row-category-${category.id}`}><td><strong>{category.name}</strong><span className="table-secondary">{category.slug}</span></td><td>{category.description || 'No description'}</td><td><StatusBadge value={category.is_active} /></td><td><div className="table-actions"><ActionButton onClick={() => edit(category)} testId={`button-edit-category-${category.id}`}><Pencil size={14} /> Edit</ActionButton><ConfirmButton label="Delete" onConfirm={async () => { try { await adminApi.categories.remove(category.id); result.reload(); } catch (error) { window.alert(errorMessage(error)); } }} danger /></div></td></tr>)}</tbody></table></div></div>}</>;
}

function AdvertisementsPage() {
  const [approval, setApproval] = useState(''); const [payment, setPayment] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const result = useLoad(() => adminApi.advertisements.list({ approval, payment, search, page, limit: 20 }), [approval, payment, search, page]); const [saving, setSaving] = useState('');
  const action = async (ad: Advertisement, type: 'approve' | 'reject' | 'pause' | 'delete') => { setSaving(ad.id); try { if (type === 'approve') await adminApi.advertisements.approve(ad.id); if (type === 'reject') await adminApi.advertisements.reject(ad.id, window.prompt('Rejection reason', 'Inappropriate content') || 'Inappropriate content'); if (type === 'pause') await adminApi.advertisements.pause(ad.id); if (type === 'delete') await adminApi.advertisements.remove(ad.id); result.reload(); } catch (error) { window.alert(errorMessage(error)); } finally { setSaving(''); } };
  const ads = result.data?.data || [];
  return <><PageHeader eyebrow="PROMOTIONS" title="Advertisements" detail="Review paid promotion requests and active campaign status." /><Toolbar><div className="search-box"><Search size={16} /><Input value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Search title or description" testId="input-ad-search" /></div><select className="select" value={approval} onChange={(event) => { setApproval(event.target.value); setPage(1); }} data-testid="select-ad-approval"><option value="">All approvals</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="paused">Paused</option></select><select className="select" value={payment} onChange={(event) => { setPayment(event.target.value); setPage(1); }} data-testid="select-ad-payment"><option value="">All payments</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="failed">Failed</option></select></Toolbar>{result.loading ? <SkeletonTable /> : result.error ? <PageError message={result.error} retry={result.reload} /> : ads.length === 0 ? <EmptyState title="No advertisements found" /> : <div className="panel"><div className="scroll-table"><table className="data-table"><thead><tr><th>Campaign</th><th>Advertiser</th><th>Duration</th><th>Payment</th><th>Approval</th><th>Expiry</th><th>Actions</th></tr></thead><tbody>{ads.map((ad) => <tr key={ad.id} data-testid={`row-ad-${ad.id}`}><td><Link href={`/advertisements/${ad.id}`} className="table-primary">{ad.title}</Link><span className="table-secondary">{formatDate(ad.created_at)}</span></td><td>{ad.user?.full_name || ad.user?.username || 'Unavailable'}</td><td>{ad.duration_days} days <span className="table-secondary">{formatMoney(ad.amount)}</span></td><td><StatusBadge value={ad.payment_status} /></td><td><StatusBadge value={ad.approval_status} /></td><td>{formatDate(ad.expires_at)}</td><td><div className="table-actions">{ad.approval_status === 'pending' && <ActionButton onClick={() => action(ad, 'approve')} disabled={saving === ad.id} testId={`button-approve-ad-${ad.id}`}><Check size={14} /> Approve</ActionButton>}{ad.approval_status !== 'rejected' && <ActionButton onClick={() => action(ad, 'reject')} disabled={saving === ad.id} testId={`button-reject-ad-${ad.id}`}><X size={14} /> Reject</ActionButton>}{ad.approval_status === 'approved' && <ActionButton onClick={() => action(ad, 'pause')} disabled={saving === ad.id} testId={`button-pause-ad-${ad.id}`}><Clock3 size={14} /> Pause</ActionButton>}<ConfirmButton label="Delete" onConfirm={() => action(ad, 'delete')} danger disabled={saving === ad.id} /></div></td></tr>)}</tbody></table></div><Pagination page={page} totalPages={result.data?.pagination?.totalPages} onChange={setPage} /></div>}</>;
}

function AdvertisementDetail({ adId }: { adId: string }) {
  const result = useLoad(() => adminApi.advertisements.get(adId), [adId]); const [, setLocation] = useLocation(); const [busy, setBusy] = useState(false);
  if (result.loading) return <><PageHeader title="Advertisement details" /><SkeletonTable /></>; if (result.error || !result.data) return <PageError message={result.error || 'Advertisement not found'} retry={result.reload} />;
  const ad = result.data; const action = async (type: 'approve' | 'reject' | 'pause') => { setBusy(true); try { if (type === 'approve') await adminApi.advertisements.approve(ad.id); if (type === 'reject') await adminApi.advertisements.reject(ad.id, window.prompt('Rejection reason', 'Inappropriate content') || 'Inappropriate content'); if (type === 'pause') await adminApi.advertisements.pause(ad.id); result.reload(); } catch (error) { window.alert(errorMessage(error)); } finally { setBusy(false); } };
  return <><button className="back-link" onClick={() => setLocation('/advertisements')} data-testid="button-back-ads"><ArrowLeft size={15} /> Back to advertisements</button><PageHeader eyebrow="CAMPAIGN INSPECTION" title={ad.title} detail={`Created ${formatDate(ad.created_at)}`} action={<div className="header-actions"><ActionButton primary onClick={() => action('approve')} disabled={busy} testId="button-detail-ad-approve"><Check size={15} /> Approve</ActionButton><ActionButton onClick={() => action('reject')} disabled={busy} testId="button-detail-ad-reject"><X size={15} /> Reject</ActionButton></div>} /><div className="detail-grid"><div className="panel">{ad.image_url ? <img className="ad-preview" src={ad.image_url} alt={ad.title} /> : <div className="ad-preview ad-empty"><Megaphone size={30} /></div>}<h3>{ad.title}</h3><p className="detail-description">{ad.description || 'No description provided.'}</p><div className="field-grid"><div><span className="field-label">Payment</span><StatusBadge value={ad.payment_status} /></div><div><span className="field-label">Approval</span><StatusBadge value={ad.approval_status} /></div><div><span className="field-label">Amount</span><strong>{formatMoney(ad.amount)}</strong></div><div><span className="field-label">Duration</span><strong>{ad.duration_days} days</strong></div><div><span className="field-label">Expires</span><strong>{formatDate(ad.expires_at)}</strong></div></div></div><div className="panel"><span className="eyebrow">ADVERTISER</span><h3>{ad.user?.full_name || ad.user?.username || 'Unavailable'}</h3><p className="muted">{ad.user?.email || 'Email unavailable.'}</p><div className="detail-danger"><ActionButton onClick={() => action('pause')} disabled={busy} testId="button-detail-ad-pause"><Clock3 size={14} /> Pause campaign</ActionButton></div></div></div></>;
}

function DurationsPage() {
  const result = useLoad(() => adminApi.durations.list(), []); const [editing, setEditing] = useState<Duration | null>(null); const [form, setForm] = useState({ days: '', price: '', active: true }); const [busy, setBusy] = useState(false);
  const save = async () => { setBusy(true); try { const payload = { duration_days: Number(form.days), price: Number(form.price), is_active: form.active }; if (editing?.id) await adminApi.durations.update(editing.id, payload); else await adminApi.durations.create(payload); setEditing(null); result.reload(); } catch (error) { window.alert(errorMessage(error)); } finally { setBusy(false); } };
  return <><PageHeader eyebrow="ADVERTISEMENT CONFIGURATION" title="Ad pricing" detail="Duration and price options are read and written through the admin API." action={<ActionButton primary onClick={() => { setEditing({ id: '', duration_days: 0, price: 0 }); setForm({ days: '', price: '', active: true }); }} testId="button-add-duration"><Plus size={15} /> Add duration</ActionButton>} />{editing && <div className="panel editor-panel"><div className="panel-heading"><div><span className="eyebrow">{editing.id ? 'EDIT OPTION' : 'NEW OPTION'}</span><h3>{editing.id ? 'Update pricing' : 'Create pricing'}</h3></div><button className="icon-button" onClick={() => setEditing(null)} aria-label="Close editor"><X size={17} /></button></div><div className="form-grid"><label>Duration in days<input className="input" type="number" min="1" value={form.days} onChange={(event) => setForm({ ...form, days: event.target.value })} data-testid="input-duration-days" /></label><label>Price<input className="input" type="number" min="0" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} data-testid="input-duration-price" /></label><label className="check-label"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} data-testid="input-duration-active" /> Active for new advertisements</label></div><div className="editor-actions"><ActionButton primary onClick={save} disabled={busy || !form.days || !form.price} testId="button-save-duration">{busy ? 'Saving...' : 'Save option'}</ActionButton></div></div>}{result.loading ? <SkeletonTable /> : result.error ? <PageError message={result.error} retry={result.reload} /> : !result.data?.length ? <EmptyState title="No pricing options" detail="Create the first duration supported by your marketplace." /> : <div className="panel"><div className="scroll-table"><table className="data-table"><thead><tr><th>Duration</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{result.data.map((item) => <tr key={item.id} data-testid={`row-duration-${item.id}`}><td><strong>{item.duration_days} days</strong></td><td className="money">{formatMoney(item.price)}</td><td><StatusBadge value={item.is_active} /></td><td><div className="table-actions"><ActionButton onClick={() => { setEditing(item); setForm({ days: String(item.duration_days), price: String(item.price), active: item.is_active !== false }); }} testId={`button-edit-duration-${item.id}`}><Pencil size={14} /> Edit</ActionButton><ConfirmButton label="Delete" onConfirm={async () => { try { await adminApi.durations.remove(item.id); result.reload(); } catch (error) { window.alert(errorMessage(error)); } }} danger /></div></td></tr>)}</tbody></table></div></div>}</>;
}

function PaymentsPage() {
  const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const result = useLoad(() => adminApi.payments.list({ status, search, page, limit: 20 }), [status, search, page]); const stats = useLoad(() => adminApi.payments.stats(), []);
  const payments = result.data?.data || [];
  return <><PageHeader eyebrow="FINANCE" title="Payments" detail="Advertisement transactions returned by the SHINEX payment records." /><div className="finance-strip"><div><span className="eyebrow">TOTAL REVENUE</span><strong>{stats.data ? formatMoney(stats.data.total_revenue) : stats.loading ? 'Loading…' : 'Unavailable'}</strong></div><div><span className="eyebrow">TRANSACTIONS</span><strong>{stats.data?.total_transactions ?? (stats.loading ? 'Loading…' : 'Unavailable')}</strong></div><div><span className="eyebrow">STATUS DATA</span><strong>{stats.data?.status_breakdown?.length ?? (stats.loading ? 'Loading…' : 'Unavailable')}</strong></div></div><Toolbar><div className="search-box"><Search size={16} /><Input value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Search reference or account" testId="input-payment-search" /></div><select className="select" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} data-testid="select-payment-status"><option value="">All statuses</option><option value="success">Success</option><option value="pending">Pending</option><option value="failed">Failed</option></select></Toolbar>{result.loading ? <SkeletonTable /> : result.error ? <PageError message={result.error} retry={result.reload} /> : !payments.length ? <EmptyState title="No payments found" /> : <div className="panel"><div className="scroll-table"><table className="data-table"><thead><tr><th>Reference</th><th>User</th><th>Advertisement</th><th>Amount</th><th>Status</th><th>Paid</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id} data-testid={`row-payment-${payment.id}`}><td><Link href={`/payments/${payment.id}`} className="table-primary mono">{payment.paystack_reference || short(payment.id)}</Link></td><td>{payment.user?.full_name || payment.user?.username || 'Unavailable'}<span className="table-secondary">{payment.user?.email}</span></td><td>{payment.advertisement?.title || 'Unavailable'}</td><td className="money">{formatMoney(Number(payment.amount))}</td><td><StatusBadge value={payment.status} /></td><td>{formatDate(payment.paid_at || payment.created_at)}</td></tr>)}</tbody></table></div><Pagination page={page} totalPages={result.data?.pagination?.totalPages} onChange={setPage} /></div>}</>;
}

function PaymentDetail({ paymentId }: { paymentId: string }) {
  const result = useLoad(() => adminApi.payments.get(paymentId), [paymentId]); const [, setLocation] = useLocation();
  if (result.loading) return <><PageHeader title="Payment details" /><SkeletonTable /></>; if (result.error || !result.data) return <PageError message={result.error || 'Payment not found'} retry={result.reload} />; const payment = result.data;
  return <><button className="back-link" onClick={() => setLocation('/payments')} data-testid="button-back-payments"><ArrowLeft size={15} /> Back to payments</button><PageHeader eyebrow="TRANSACTION RECORD" title={payment.paystack_reference || payment.id} detail={`Created ${formatDate(payment.created_at)}`} /><div className="panel detail-panel"><div className="field-grid"><div><span className="field-label">Amount</span><strong className="money">{formatMoney(Number(payment.amount))}</strong></div><div><span className="field-label">Status</span><StatusBadge value={payment.status} /></div><div><span className="field-label">Paid at</span><strong>{formatDate(payment.paid_at)}</strong></div><div><span className="field-label">Payment ID</span><strong className="mono">{payment.id}</strong></div><div><span className="field-label">User</span><strong>{payment.user?.full_name || payment.user?.username || 'Unavailable'}</strong><span className="table-secondary">{payment.user?.email}</span></div><div><span className="field-label">Advertisement</span><strong>{payment.advertisement?.title || 'Unavailable'}</strong><span className="table-secondary">{payment.advertisement?.duration_days ? `${payment.advertisement.duration_days} days` : ''}</span></div></div></div></>;
}

function ReportsPage() {
  const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const result = useLoad(() => adminApi.reports.list({ status, page, limit: 20 }), [status, page]); const reports = result.data?.data || [];
  const action = async (report: Report, type: 'resolve' | 'dismiss') => { try { const notes = window.prompt(`${type === 'resolve' ? 'Resolution' : 'Dismissal'} notes`, type === 'resolve' ? 'Reviewed by admin' : 'No policy violation found') || ''; if (type === 'resolve') await adminApi.reports.resolve(report.id, notes); else await adminApi.reports.dismiss(report.id, notes); result.reload(); } catch (error) { window.alert(errorMessage(error)); } };
  return <><PageHeader eyebrow="TRUST & SAFETY" title="Reports" detail="Review user-submitted reports and record the backend-supported outcome." /><Toolbar><select className="select" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} data-testid="select-report-status"><option value="">All statuses</option><option value="pending">Pending</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></Toolbar>{result.loading ? <SkeletonTable /> : result.error ? <PageError message={result.error} retry={result.reload} /> : !reports.length ? <EmptyState title="No reports found" /> : <div className="panel"><div className="scroll-table"><table className="data-table"><thead><tr><th>Reason</th><th>Reporter</th><th>Target</th><th>Status</th><th>Received</th><th>Actions</th></tr></thead><tbody>{reports.map((report) => <tr key={report.id} data-testid={`row-report-${report.id}`}><td><Link href={`/reports/${report.id}`} className="table-primary">{report.reason}</Link><span className="table-secondary">{short(report.description, 48)}</span></td><td>{report.reporter?.full_name || report.reporter?.username || 'Unavailable'}</td><td>{report.target_product?.name || report.target_user?.username || report.target_advertisement?.title || 'Unavailable'}</td><td><StatusBadge value={report.status} /></td><td>{formatDate(report.created_at)}</td><td>{report.status === 'pending' && <div className="table-actions"><ActionButton primary onClick={() => action(report, 'resolve')} testId={`button-resolve-report-${report.id}`}><Check size={14} /> Resolve</ActionButton><ActionButton onClick={() => action(report, 'dismiss')} testId={`button-dismiss-report-${report.id}`}><X size={14} /> Dismiss</ActionButton></div>}</td></tr>)}</tbody></table></div><Pagination page={page} totalPages={result.data?.pagination?.totalPages} onChange={setPage} /></div>}</>;
}

function ReportDetail({ reportId }: { reportId: string }) {
  const result = useLoad(() => adminApi.reports.get(reportId), [reportId]); const [, setLocation] = useLocation();
  if (result.loading) return <><PageHeader title="Report details" /><SkeletonTable /></>; if (result.error || !result.data) return <PageError message={result.error || 'Report not found'} retry={result.reload} />; const report = result.data;
  const act = async (type: 'resolve' | 'dismiss') => { try { const notes = window.prompt('Admin notes', type === 'resolve' ? 'Reviewed by admin' : 'No policy violation found') || ''; if (type === 'resolve') await adminApi.reports.resolve(report.id, notes); else await adminApi.reports.dismiss(report.id, notes); result.reload(); } catch (error) { window.alert(errorMessage(error)); } };
  return <><button className="back-link" onClick={() => setLocation('/reports')} data-testid="button-back-reports"><ArrowLeft size={15} /> Back to reports</button><PageHeader eyebrow="REPORT INSPECTION" title={report.reason} detail={`Received ${formatDate(report.created_at)}`} action={report.status === 'pending' && <div className="header-actions"><ActionButton primary onClick={() => act('resolve')} testId="button-detail-resolve"><Check size={15} /> Resolve</ActionButton><ActionButton onClick={() => act('dismiss')} testId="button-detail-dismiss"><X size={15} /> Dismiss</ActionButton></div>} /><div className="panel detail-panel"><div className="field-grid"><div><span className="field-label">Status</span><StatusBadge value={report.status} /></div><div><span className="field-label">Reporter</span><strong>{report.reporter?.full_name || report.reporter?.username || 'Unavailable'}</strong><span className="table-secondary">{report.reporter?.email}</span></div><div><span className="field-label">Reported product</span><strong>{report.target_product?.name || 'Not a product report'}</strong></div><div><span className="field-label">Reported user</span><strong>{report.target_user?.full_name || report.target_user?.username || 'Not a user report'}</strong></div></div><div className="long-copy"><span className="field-label">Description</span><p>{report.description || 'No description supplied.'}</p></div>{report.admin_notes && <div className="long-copy"><span className="field-label">Admin notes</span><p>{report.admin_notes}</p></div>}</div></>;
}

function ContactPage() {
  const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const result = useLoad(() => adminApi.contact.list({ status, search, page, limit: 20 }), [status, search, page]); const messages = result.data?.data || [];
  const changeStatus = async (message: ContactMessage, next: ContactMessage['status']) => { try { await adminApi.contact.status(message.id, next); result.reload(); } catch (error) { window.alert(errorMessage(error)); } };
  return <><PageHeader eyebrow="SUPPORT INBOX" title="Contact messages" detail="Read inbound support messages and keep their response status current." /><Toolbar><div className="search-box"><Search size={16} /><Input value={search} onChange={(value) => { setSearch(value); setPage(1); }} placeholder="Search sender, subject or message" testId="input-contact-search" /></div><select className="select" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} data-testid="select-contact-status"><option value="">All statuses</option><option value="new">New</option><option value="read">Read</option><option value="replied">Replied</option></select></Toolbar>{result.loading ? <SkeletonTable /> : result.error ? <PageError message={result.error} retry={result.reload} /> : !messages.length ? <EmptyState title="Inbox is clear" detail="No contact messages match this view." /> : <div className="panel"><div className="scroll-table"><table className="data-table"><thead><tr><th>Sender</th><th>Subject</th><th>Message</th><th>Status</th><th>Received</th><th>Actions</th></tr></thead><tbody>{messages.map((message) => <tr key={message.id} data-testid={`row-contact-${message.id}`}><td><Link className="table-primary" href={`/contact/${message.id}`}>{message.name}</Link><span className="table-secondary">{message.email}</span></td><td>{message.subject}</td><td>{short(message.message, 50)}</td><td><StatusBadge value={message.status} /></td><td>{formatDate(message.created_at)}</td><td><div className="table-actions"><select className="mini-select" value={message.status} onChange={(event) => changeStatus(message, event.target.value as ContactMessage['status'])} data-testid={`select-contact-status-${message.id}`}><option value="new">New</option><option value="read">Read</option><option value="replied">Replied</option></select><ConfirmButton label="Delete" onConfirm={async () => { try { await adminApi.contact.remove(message.id); result.reload(); } catch (error) { window.alert(errorMessage(error)); } }} danger /></div></td></tr>)}</tbody></table></div><Pagination page={page} totalPages={result.data?.pagination?.totalPages} onChange={setPage} /></div>}</>;
}

function ContactDetail({ messageId }: { messageId: string }) {
  const result = useLoad(() => adminApi.contact.get(messageId), [messageId]); const [, setLocation] = useLocation();
  if (result.loading) return <><PageHeader title="Message details" /><SkeletonTable /></>; if (result.error || !result.data) return <PageError message={result.error || 'Message not found'} retry={result.reload} />; const message = result.data;
  const changeStatus = async (status: ContactMessage['status']) => { try { await adminApi.contact.status(message.id, status); result.reload(); } catch (error) { window.alert(errorMessage(error)); } };
  return <><button className="back-link" onClick={() => setLocation('/contact')} data-testid="button-back-contact"><ArrowLeft size={15} /> Back to contact</button><PageHeader eyebrow="SUPPORT MESSAGE" title={message.subject} detail={`Received ${formatDate(message.created_at)}`} /><div className="panel message-detail"><div className="message-meta"><div className="avatar-large">{message.name.slice(0, 1).toUpperCase()}</div><div><h3>{message.name}</h3><p>{message.email} {message.phone && `· ${message.phone}`}</p></div><StatusBadge value={message.status} /></div><div className="long-copy"><span className="field-label">Message</span><p>{message.message}</p></div><div className="editor-actions"><ActionButton onClick={() => changeStatus('new')} testId="button-message-new">Mark new</ActionButton><ActionButton onClick={() => changeStatus('read')} testId="button-message-read">Mark read</ActionButton><ActionButton primary onClick={() => changeStatus('replied')} testId="button-message-replied">Mark replied</ActionButton></div></div></>;
}

function UnsupportedPage({ title, reason }: { title: string; reason: string }) { return <><PageHeader eyebrow="BACKEND CAPABILITY" title={title} detail="This route is intentionally visible so the boundary is clear." /><div className="unsupported"><Settings size={25} /><h3>Not supported by the current SHINEX API</h3><p>{reason}</p><span>Nothing is stored locally and no unsupported request is made.</span></div></>; }

function UserDetailRoute() { const { id = '' } = useParams<{ id: string }>(); return <AuthGate>{() => <UserDetail userId={id} />}</AuthGate>; }
function ProductDetailRoute() { const { id = '' } = useParams<{ id: string }>(); return <AuthGate>{() => <ProductDetail productId={id} />}</AuthGate>; }
function AdvertisementDetailRoute() { const { id = '' } = useParams<{ id: string }>(); return <AuthGate>{() => <AdvertisementDetail adId={id} />}</AuthGate>; }
function PaymentDetailRoute() { const { id = '' } = useParams<{ id: string }>(); return <AuthGate>{() => <PaymentDetail paymentId={id} />}</AuthGate>; }
function ReportDetailRoute() { const { id = '' } = useParams<{ id: string }>(); return <AuthGate>{() => <ReportDetail reportId={id} />}</AuthGate>; }
function ContactDetailRoute() { const { id = '' } = useParams<{ id: string }>(); return <AuthGate>{() => <ContactDetail messageId={id} />}</AuthGate>; }

function Router() {
  return <ErrorBoundary><Switch>
    <Route path="/login" component={Login} />
    <Route path="/dashboard">{() => <AuthGate>{() => <Dashboard />}</AuthGate>}</Route>
    <Route path="/users">{() => <AuthGate>{() => <UsersPage />}</AuthGate>}</Route>
    <Route path="/users/:id" component={UserDetailRoute} />
    <Route path="/products">{() => <AuthGate>{() => <ProductsPage />}</AuthGate>}</Route>
    <Route path="/products/:id" component={ProductDetailRoute} />
    <Route path="/categories">{() => <AuthGate>{() => <CategoriesPage />}</AuthGate>}</Route>
    <Route path="/advertisements">{() => <AuthGate>{() => <AdvertisementsPage />}</AuthGate>}</Route>
    <Route path="/advertisements/:id" component={AdvertisementDetailRoute} />
    <Route path="/durations">{() => <AuthGate>{() => <DurationsPage />}</AuthGate>}</Route>
    <Route path="/payments">{() => <AuthGate>{() => <PaymentsPage />}</AuthGate>}</Route>
    <Route path="/payments/:id" component={PaymentDetailRoute} />
    <Route path="/reports">{() => <AuthGate>{() => <ReportsPage />}</AuthGate>}</Route>
    <Route path="/reports/:id" component={ReportDetailRoute} />
    <Route path="/contact">{() => <AuthGate>{() => <ContactPage />}</AuthGate>}</Route>
    <Route path="/contact/:id" component={ContactDetailRoute} />
    <Route path="/settings">{() => <AuthGate>{() => <UnsupportedPage title="Settings" reason="The documented backend exposes no admin settings read or write endpoints. Marketplace configuration remains backend-owned." />}</AuthGate>}</Route>
    <Route path="/admin-management">{() => <AuthGate>{() => <UsersPage management />}</AuthGate>}</Route>
    <Route path="/audit-logs">{() => <AuthGate>{() => <UnsupportedPage title="Audit logs" reason="The documented SHINEX admin API does not expose audit log endpoints. This console does not invent an audit trail." />}</AuthGate>}</Route>
    <Route path="/">{() => getToken() ? <Redirect to="/dashboard" /> : <Redirect to="/login" />}</Route>
    <Route component={NotFound} />
  </Switch></ErrorBoundary>;
}

export default function App() {
  return (
    <WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}>
      <Router />
    </WouterRouter>
  );
}